"""empty message

Revision ID: b192a8afcb20
Revises: 39291c1eefb4
Create Date: 2024-10-06 15:33:42.474015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b192a8afcb20'
down_revision: Union[str, None] = '39291c1eefb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'size')
    # ### end Alembic commands ###
